import React from 'react';
import { Button } from 'react-bootstrap';

const LyricCardPreview = ({ line, artist, title, coverUrl, exportCardAsImage }) => {
  if (!line) return null;

 return (
  <div className="card-preview">
    <div id="card-to-export" className="card-content">
      
      {/*Testo mio sito posizionato sopra alla cover */}
      <p className="card-brand">
        Generated by <strong>Fuori di testo</strong>
      </p>

      <img
        src={coverUrl}
        className="card-cover"
        alt="cover"
        crossOrigin="anonymous"
      />

      <p className="lyric-text gold-text">“{line}”</p>
      <p className="card-meta gold-text">
        {decodeURIComponent(artist)} – {decodeURIComponent(title)}
      </p>
    </div>

    {/* Questo bottone NON sarà nell'immagine esportata */}
    <Button
      onClick={exportCardAsImage}
      className="glow-button bg-dark mt-3 w-100 gold-text"
    >
      Scarica card e condividila nelle stories
    </Button>
  </div>
);

};

export default LyricCardPreview;
